FROM continuumio/miniconda3

RUN conda install -c conda-forge pymc3
RUN conda install -c conda-forge arviz=0.11.0
RUN conda install -c conda-forge jupyterlab
RUN pip install git+https://github.com/ColCarroll/imcmc

